#!/usr/bin/env bash
set -euo pipefail

# Mailu DNS Configuration Script
# Automates creation of MX, A/AAAA, SPF, DKIM, and DMARC records via Cloudflare API
# Requires: CLOUDFLARE_API_TOKEN in .env file

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

# Load environment variables
if [ ! -f "$ENV_FILE" ]; then
    echo "❌ Error: .env file not found at $ENV_FILE"
    exit 1
fi

source "$ENV_FILE"

# Required variables
DOMAIN="${DOMAIN:-inlock.ai}"
EMAIL="${EMAIL:-admin@inlock.ai}"
CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"

if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
    echo "❌ Error: CLOUDFLARE_API_TOKEN not set in .env"
    exit 1
fi

# Get server IP (try to detect from hostname or ask user)
SERVER_IP="${SERVER_IP:-}"
if [ -z "$SERVER_IP" ]; then
    echo "❌ Error: SERVER_IP environment variable is not set."
    exit 1
fi
echo "✅ Using server IP: $SERVER_IP"

SERVER_IPV6="${SERVER_IPV6:-}"
if [ -n "$SERVER_IPV6" ]; then
    echo "✅ Using server IPv6: $SERVER_IPV6"
fi

# Get Cloudflare Zone ID
echo "📡 Fetching Cloudflare zone information for $DOMAIN..."
ZONE_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    -H "Content-Type: application/json")

ZONE_ID=$(echo "$ZONE_RESPONSE" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)

if [ -z "$ZONE_ID" ]; then
    echo "❌ Error: Could not find Cloudflare zone for $DOMAIN"
    echo "Response: $ZONE_RESPONSE"
    exit 1
fi

echo "✅ Found zone ID: $ZONE_ID"

# Function to create or update DNS record
create_or_update_record() {
    local record_type=$1
    local record_name=$2
    local record_content=$3
    local priority=${4:-""}
    local ttl=${5:-3600}  # Default TTL 1 hour
    
    echo ""
    echo "📝 Processing $record_type record: $record_name"
    
    # Check if record exists
    EXISTING_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?type=$record_type&name=$record_name" \
        -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
        -H "Content-Type: application/json")
    
    RECORD_ID=$(echo "$EXISTING_RECORDS" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4 || echo "")
    
    # Build request body
    if [ -n "$priority" ]; then
        BODY="{\"type\":\"$record_type\",\"name\":\"$record_name\",\"content\":\"$record_content\",\"ttl\":$ttl,\"priority\":$priority}"
    else
        BODY="{\"type\":\"$record_type\",\"name\":\"$record_name\",\"content\":\"$record_content\",\"ttl\":$ttl}"
    fi
    
    if [ -n "$RECORD_ID" ]; then
        echo "   ℹ️  Record exists, updating..."
        RESPONSE=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$BODY")
    else
        echo "   ➕ Creating new record..."
        RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$BODY")
    fi
    
    # Check response
    SUCCESS=$(echo "$RESPONSE" | grep -o '"success":true' || echo "")
    if [ -n "$SUCCESS" ]; then
        echo "   ✅ Success"
    else
        echo "   ❌ Failed: $RESPONSE"
        return 1
    fi
}

# 1. Create A record for mail subdomain
create_or_update_record "A" "mail.$DOMAIN" "$SERVER_IP"

# 2. Create AAAA record for mail subdomain (if IPv6 provided)
if [ -n "$SERVER_IPV6" ]; then
    create_or_update_record "AAAA" "mail.$DOMAIN" "$SERVER_IPV6"
fi

# 3. Create MX record
create_or_update_record "MX" "$DOMAIN" "mail.$DOMAIN" "10"

# 4. Create SPF record
SPF_CONTENT="v=spf1 mx a:mail.$DOMAIN ~all"
create_or_update_record "TXT" "$DOMAIN" "$SPF_CONTENT"

# 5. Create DMARC record
DMARC_CONTENT="v=DMARC1; p=quarantine; rua=mailto:$EMAIL; ruf=mailto:$EMAIL; fo=1"
create_or_update_record "TXT" "_dmarc.$DOMAIN" "$DMARC_CONTENT"

# 6. DKIM record (needs to be extracted from Mailu after deployment)
echo ""
echo "⚠️  DKIM Record Setup"
echo "   DKIM keys are generated by Mailu after first deployment."
echo "   To get the DKIM public key, run:"
echo "   docker exec compose-mailu-admin-1 cat /dkim/\$DOMAIN.txt"
echo ""
   echo "   Then create a TXT record:"
   echo "   Name: mail._domainkey.$DOMAIN"
   echo "   Content: [paste DKIM public key from above command]"
echo ""

# Summaryecho ""
echo "✅ DNS Configuration Complete!"
echo ""
echo "📋 Summary of records created:"
echo "   - A record: mail.$DOMAIN → $SERVER_IP"
[ -n "$SERVER_IPV6" ] && echo "   - AAAA record: mail.$DOMAIN → $SERVER_IPV6"
echo "   - MX record: $DOMAIN → mail.$DOMAIN (priority 10)"
echo "   - SPF record: $DOMAIN → $SPF_CONTENT"
echo "   - DMARC record: _dmarc.$DOMAIN → $DMARC_CONTENT"
echo "   - DKIM record: [Manual - see instructions above]"
echo ""
echo "⏳ DNS propagation typically takes 5-60 minutes"
echo "   Verify with: dig MX $DOMAIN"
echo ""
