#!/bin/bash
# Comprehensive security maintenance script
# Runs all security checks and generates report

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
REPORT_DIR="$PROJECT_ROOT/docs/security/maintenance-reports"
REPORT_FILE="$REPORT_DIR/maintenance-report-$TIMESTAMP.md"

mkdir -p "$REPORT_DIR"

echo "=========================================="
echo "  Security Maintenance"
echo "=========================================="
echo ""
echo "Timestamp: $(date)"
echo "Report: $REPORT_FILE"
echo ""

# Start report
cat > "$REPORT_FILE" << EOF
# Security Maintenance Report

**Date:** $(date)
**Generated by:** security-maintenance.sh

---

## Summary

EOF

ERRORS=0
WARNINGS=0
PASSED=0

# Function to run check and record result
run_check() {
    local name="$1"
    local script="$2"
    local required_sudo="${3:-false}"
    
    echo -e "${BLUE}Running: $name${NC}"
    
    if [ "$required_sudo" = "true" ]; then
        if sudo "$script" >> "$REPORT_FILE" 2>&1; then
            echo -e "${GREEN}✓ $name passed${NC}"
            echo "**$name:** ✅ PASSED" >> "$REPORT_FILE"
            PASSED=$((PASSED + 1))
        else
            echo -e "${YELLOW}⚠️  $name has warnings${NC}"
            echo "**$name:** ⚠️ WARNINGS" >> "$REPORT_FILE"
            WARNINGS=$((WARNINGS + 1))
        fi
    else
        if "$script" >> "$REPORT_FILE" 2>&1; then
            echo -e "${GREEN}✓ $name passed${NC}"
            echo "**$name:** ✅ PASSED" >> "$REPORT_FILE"
            PASSED=$((PASSED + 1))
        else
            echo -e "${YELLOW}⚠️  $name has warnings${NC}"
            echo "**$name:** ⚠️ WARNINGS" >> "$REPORT_FILE"
            WARNINGS=$((WARNINGS + 1))
        fi
    fi
    echo "" >> "$REPORT_FILE"
    echo ""
}

# Run checks
echo "## Checks" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 1. Image version check
if [ -f "$PROJECT_ROOT/scripts/security/check-image-versions.sh" ]; then
    run_check "Image Version Check" "$PROJECT_ROOT/scripts/security/check-image-versions.sh" false
fi

# 2. Container hardening verification
if [ -f "$PROJECT_ROOT/scripts/security/verify-container-hardening.sh" ]; then
    run_check "Container Hardening" "$PROJECT_ROOT/scripts/security/verify-container-hardening.sh" false
fi

# 3. SSH restrictions
if [ -f "$PROJECT_ROOT/scripts/security/verify-ssh-restrictions.sh" ]; then
    run_check "SSH Restrictions" "$PROJECT_ROOT/scripts/security/verify-ssh-restrictions.sh" true
fi

# 4. Compose file validation
echo -e "${BLUE}Validating compose files...${NC}"
echo "## Compose File Validation" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

for compose_file in "$PROJECT_ROOT/compose/services"/*.yml; do
    if [ -f "$compose_file" ]; then
        filename=$(basename "$compose_file")
        if docker compose -f "$compose_file" config >/dev/null 2>&1; then
            echo -e "${GREEN}✓ $filename valid${NC}"
            echo "**$filename:** ✅ Valid" >> "$REPORT_FILE"
            PASSED=$((PASSED + 1))
        else
            echo -e "${RED}❌ $filename has errors${NC}"
            echo "**$filename:** ❌ ERRORS" >> "$REPORT_FILE"
            ERRORS=$((ERRORS + 1))
        fi
    fi
done
echo "" >> "$REPORT_FILE"
echo ""

# Summary
echo "=========================================="
echo "  Summary"
echo "=========================================="
echo ""

cat >> "$REPORT_FILE" << EOF
---

## Summary

- **Passed:** $PASSED
- **Warnings:** $WARNINGS
- **Errors:** $ERRORS

EOF

if [ $ERRORS -eq 0 ] && [ $WARNINGS -eq 0 ]; then
    echo -e "${GREEN}✅ All checks passed${NC}"
    echo "**Status:** ✅ ALL CHECKS PASSED" >> "$REPORT_FILE"
    STATUS=0
elif [ $ERRORS -eq 0 ]; then
    echo -e "${YELLOW}⚠️  $WARNINGS warning(s) found${NC}"
    echo "**Status:** ⚠️ WARNINGS FOUND" >> "$REPORT_FILE"
    STATUS=0
else
    echo -e "${RED}❌ $ERRORS error(s) found, $WARNINGS warning(s)${NC}"
    echo "**Status:** ❌ ERRORS FOUND" >> "$REPORT_FILE"
    STATUS=1
fi

echo ""
echo "Report saved to: $REPORT_FILE"
echo ""

exit $STATUS

