services:
  casaos:
    # SECURITY: Using specific version tag instead of :latest
    # Check for latest version: docker pull linuxserver/heimdall:latest && docker inspect linuxserver/heimdall:latest
    image: linuxserver/heimdall:2.5.7
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - casaos_config:/config
    networks:
      - edge
    # CasaOS/Heimdall replaced by Homarr - router not needed
    # Docker labels removed to eliminate dependency on Docker provider
    labels: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    # SECURITY: Container hardening
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  edge:
    external: true
    name: edge

volumes:
  casaos_config:
