# Mailu Email Stack
# Provides SMTP, IMAP, webmail, and admin interface
# Security: Hardened containers, secrets management, network isolation

networks:
  mail:
    name: mail
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
  internal:
    external: true
    name: internal
  mgmt:
    external: true
    name: mgmt
  edge:
    external: true
    name: edge

secrets:
  mailu-secret-key:
    file: /home/comzis/apps/secrets-real/mailu-secret-key
  mailu-admin-password:
    file: /home/comzis/apps/secrets-real/mailu-admin-password
  mailu-db-password:
    file: /home/comzis/apps/secrets-real/mailu-db-password

volumes:
  mailu_mail_data:
  mailu_webmail_data:
  mailu_dkim_data:
  mailu_rspamd_data:
  mailu_redis_data:
  mailu_postgres_data:
  nginx_logs:  # Front service nginx logs directory

x-default-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-hardening: &hardening
  security_opt:
    - no-new-privileges:true

x-resource-hints: &resource-hints
  deploy:
    resources:
      limits:
        memory: 512m
      reservations:
        memory: 128m

services:
  # Mailu Frontend - Webmail and Admin UI
  mailu-front:
    image: ghcr.io/mailu/nginx@sha256:1f4aa7762c0e4758cdb8c44a64b8f868a9ffea975089de38d29517390fd0d91b
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - ADMIN=true
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.25.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=notls
      - DB_FLAVOR=postgresql
      - SQLALCHEMY_DATABASE_URI=postgresql://mailu:${MAILU_DB_PASSWORD}@mailu-postgres/mailu
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_mail_data:/mail
      - mailu_dkim_data:/dkim
      - nginx_logs:/var/lib/nginx  # Writable directory for nginx logs and modules
      - ./config/nginx-front.conf:/etc/nginx/nginx.conf:ro
    ports:
      # SMTP submission - exposed directly (bypasses Traefik to avoid protocol issues)
      - "587:587"
    networks:
      mail:
        aliases:
          - front
          - mailu-front
      mgmt:
      edge:

    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/health >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 3
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging, *resource-hints]

  # Mailu Postfix - SMTP Server
  # Ports 25, 465, 587 exposed directly
  mailu-postfix:
    image: ghcr.io/mailu/postfix@sha256:5f92276dc5af71e130847fb43d6e4519b2c7f6c38b926b36374c63df8d52674f
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.25.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=notls
      - DB_FLAVOR=postgresql
      - SQLALCHEMY_DATABASE_URI=postgresql://mailu:${MAILU_DB_PASSWORD}@mailu-postgres/mailu
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
      - WEBROOT=/
    volumes:
      - mailu_mail_data:/mail
      - mailu_dkim_data:/dkim
    networks:
      mail:
        aliases:
          - postfix
      edge:
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD", "postfix", "status"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
      - /var/spool/postfix
      - /var/run
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging, *resource-hints]

  # Mailu Dovecot - IMAP Server
  mailu-imap:
    image: ghcr.io/mailu/dovecot@sha256:d089c32e3118479191ae17c3b973f014f1bdc0ebd5db192d1e4f7e41425803c5
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.25.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=notls
      - DB_FLAVOR=postgresql
      - SQLALCHEMY_DATABASE_URI=postgresql://mailu:${MAILU_DB_PASSWORD}@mailu-postgres/mailu
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_mail_data:/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/dovecot.conf:/overrides/dovecot.conf:ro
      - ./config/dummy.crt:/overrides/dummy.crt:ro
      - ./config/dummy.key:/overrides/dummy.key:ro
    networks:
      mail:
        aliases:
          - imap
      edge:
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "doveadm service status >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
      - /var/run
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
      - SYS_CHROOT
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging, *resource-hints]

  # Mailu Rspamd - Spam Filtering
  mailu-rspamd:
    image: ghcr.io/mailu/rspamd@sha256:b37566e625c696f2922dd9fa6218160c6422cd4dc93762afc254843c12649ae4
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.25.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=notls
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_rspamd_data:/var/lib/rspamd
      - ../mailu/overrides/rspamd:/etc/rspamd/override.d
    depends_on:
      - mailu-front
      - mailu-redis
    networks:
      mail:
        aliases:
          - antispam
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:11334/health >/dev/null 2>&1 || exit 0"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    tmpfs:
      - /tmp
      - /var/run
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging, *resource-hints]

  # Mailu Admin - Web UI and SSO
  # Using custom image with SSO homepage redirect fix
  mailu-admin:
    build:
      context: ./docker/mailu-admin
      dockerfile: Dockerfile
    image: mailu-admin-patched:2.0
    # Original image: ghcr.io/mailu/admin@sha256:97bc9dc7259c485fcf20bf86809b17e3aee1b236662c2ebee1f2d6c825801400
    restart: always
    # DNSSEC Required for Admin to start
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - ADMIN_USER=admin
      - ADMIN_PW_FILE=/run/secrets/mailu-admin-password
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.25.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=notls
      - DB_FLAVOR=postgresql
      - SQLALCHEMY_DATABASE_URI=postgresql://mailu:${MAILU_DB_PASSWORD}@mailu-postgres/mailu
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_mail_data:/mail
      - mailu_dkim_data:/dkim
    networks:
      mail:
        aliases:
          - admin
      mgmt:
    secrets:
      - mailu-secret-key
      - mailu-admin-password
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/ping >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
      - /var/run
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging, *resource-hints]

  # Mailu Redis - Cache and Session Storage
  mailu-redis:
    image: redis@sha256:ee64a64eaab618d88051c3ade8f6352d11531fcf79d9a4818b9b183d8c1d18ba
    restart: always
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - mailu_redis_data:/data
    networks:
      mail:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
    read_only: true
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging]

  # Mailu Postgres - Database
  mailu-postgres:
    image: postgres@sha256:a5074487380d4e686036ce61ed6f2d363939ae9a0c40123d1a9e3bb3a5f344b4
    restart: always
    environment:
      - POSTGRES_DB=mailu
      - POSTGRES_USER=mailu
      - POSTGRES_PASSWORD_FILE=/run/secrets/mailu-db-password
    volumes:
      - mailu_postgres_data:/var/lib/postgresql/data
    networks:
      mail:
        aliases:
          - postgres # Generic alias if needed
      internal:
    secrets:
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailu -d mailu"]
      interval: 30s
      timeout: 5s
      retries: 5
    tmpfs:
      - /tmp
      - /var/run/postgresql
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging, *resource-hints]

  # Webmail (Roundcube)
  # Using custom image with symlinks pre-configured
  mailu-webmail:
    build:
      context: ./docker/mailu-webmail
      dockerfile: Dockerfile
    image: mailu-webmail-custom:2.0
    # Original image: ghcr.io/mailu/webmail:2.0
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.25.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=notls
      - POSTMASTER=admin
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_webmail_data:/data

    networks:
      mail:
        aliases:
          - webmail
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/ping']
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging]
