version: '3.8'

services:
  # -------------------------------------------------------------------------
  # STRAPI (Headless CMS)
  # -------------------------------------------------------------------------
  strapi:
    build:
      context: .
      dockerfile: strapi.Dockerfile
    container_name: strapi_app
    restart: unless-stopped
    env_file: .env.tooling
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi_db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${STRAPI_DB_NAME:-strapi}
      DATABASE_USERNAME: ${STRAPI_DB_USER:-strapi}
      DATABASE_PASSWORD: ${STRAPI_DB_PASSWORD:?Required}
      DATABASE_SSL: 'false'
      NODE_ENV: production
    command: >
      /bin/sh -c "if [ ! -f package.json ]; then 
        yes n | npx -y create-strapi-app@latest . --no-run --ts --dbclient=postgres --dbhost=strapi_db --dbport=5432 --dbname=$${DATABASE_NAME} --dbusername=$${DATABASE_USERNAME} --dbpassword=$${DATABASE_PASSWORD} --dbssl=false --skip-cloud; 
      fi &&  npm install &&  npm run build &&  npm run start"
    volumes:
      - strapi_data:/srv/app
    networks:
      - tooling_net
      - traefik_public
    depends_on:
      - strapi_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`${CMS_HOSTNAME}`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=letsen"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"

  strapi_db:
    image: postgres@sha256:2e7b888f221193cddee9ce554d3311dc8be197a5d0c904fe30f5f568e0f99851
    container_name: strapi_db
    restart: unless-stopped
    env_file: .env.tooling
    environment:
      POSTGRES_USER: ${STRAPI_DB_USER:-strapi}
      POSTGRES_PASSWORD: ${STRAPI_DB_PASSWORD:?Required}
      POSTGRES_DB: ${STRAPI_DB_NAME:-strapi}
    volumes:
      - strapi_pg_data:/var/lib/postgresql/data
    networks:
      - tooling_net

  # -------------------------------------------------------------------------
  # POSTHOG (Product Analytics)
  # Based on PostHog's standard docker-compose
  # -------------------------------------------------------------------------
  posthog_db:
    image: postgres@sha256:2e7b888f221193cddee9ce554d3311dc8be197a5d0c904fe30f5f568e0f99851
    container_name: posthog_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTHOG_DB_PASSWORD:?Required}
      POSTGRES_DB: posthog
      POSTGRES_USER: posthog
    volumes:
      - posthog_pg_data:/var/lib/postgresql/data
    networks:
      - tooling_net

  posthog_redis:
    image: redis@sha256:37e002448575b32a599109664107e374c8709546905c372a34d64919043b9ceb
    container_name: posthog_redis
    restart: unless-stopped
    networks:
      - tooling_net

  # ClickHouse for analytics data
  posthog_clickhouse:
    image: clickhouse/clickhouse-server@sha256:c3f166f4a80098480463d897a63f6867d24e3a7661fc1fe72e889788115a25f1
    container_name: posthog_clickhouse
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - posthog_clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${POSTHOG_CLICKHOUSE_PASSWORD:?Required}
      - CLICKHOUSE_DB=posthog
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
    networks:
      - tooling_net

  # Kafka + Zookeeper for event ingestion
  posthog_zookeeper:
    image: confluentinc/cp-zookeeper@sha256:02f6c042bb9a7844382fc4cedc513a44585d8a5acae873fb9e510e3ca9dcabc6
    container_name: posthog_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - tooling_net

  posthog_kafka:
    image: confluentinc/cp-kafka@sha256:fbbb6fa11b258a88b83f54d4f0bddfcffbf2279f99d66a843486e3da7bdfbf41
    container_name: posthog_kafka
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'posthog_zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://posthog_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - posthog_zookeeper
    networks:
      - tooling_net

  # PostHog Web (Django app)
  posthog_web:
    image: posthog/posthog@sha256:3079e0b6a10bbda02f0f325fcf0051316957b22a7800890e9811dc053f758761
    container_name: posthog_web
    restart: unless-stopped
    env_file: .env.tooling
    environment:
      - DATABASE_URL=postgres://posthog:${POSTHOG_DB_PASSWORD}@posthog_db:5432/posthog
      - REDIS_URL=redis://posthog_redis:6379/
      - CLICKHOUSE_HOST=posthog_clickhouse
      - CLICKHOUSE_HOST=posthog_clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_SECURE=false
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${POSTHOG_CLICKHOUSE_PASSWORD:?Required}
      - CLICKHOUSE_DATABASE=posthog
      - KAFKA_URL=kafka://posthog_kafka:9092
      - SITE_URL=https://${ANALYTICS_HOSTNAME}
      - IS_BEHIND_PROXY=True
      - DISABLE_SECURE_SSL_REDIRECT=True # Handled by Traefik
    depends_on:
      - posthog_db
      - posthog_redis
      - posthog_clickhouse
      - posthog_kafka
    networks:
      - tooling_net
      - traefik_public

  # PostHog Async Workers
  posthog_worker:
    image: posthog/posthog@sha256:3079e0b6a10bbda02f0f325fcf0051316957b22a7800890e9811dc053f758761
    container_name: posthog_worker
    restart: unless-stopped
    command: ./bin/docker-worker
    env_file: .env.tooling
    environment:
      - WEB_CONCURRENCY=2
      - CLICKHOUSE_HOST=posthog_clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_SECURE=false
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${POSTHOG_CLICKHOUSE_PASSWORD:?Required}
      - DATABASE_URL=postgres://posthog:${POSTHOG_DB_PASSWORD}@posthog_db:5432/posthog
      - REDIS_URL=redis://posthog_redis:6379/
      - CLICKHOUSE_DATABASE=posthog
      - KAFKA_URL=kafka://posthog_kafka:9092
      - SITE_URL=https://${ANALYTICS_HOSTNAME}
    depends_on:
      - posthog_db
      - posthog_redis
      - posthog_clickhouse
      - posthog_kafka
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    networks:
      - tooling_net

  posthog_plugins:
    image: posthog/posthog@sha256:3079e0b6a10bbda02f0f325fcf0051316957b22a7800890e9811dc053f758761
    container_name: posthog_plugins
    restart: unless-stopped
    command: ./bin/plugin-server
    env_file: .env.tooling
    environment:
      - DATABASE_URL=postgres://posthog:${POSTHOG_DB_PASSWORD}@posthog_db:5432/posthog
      - REDIS_URL=redis://posthog_redis:6379/
      - CLICKHOUSE_HOST=posthog_clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_SECURE=false
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${POSTHOG_CLICKHOUSE_PASSWORD:?Required}
      - CLICKHOUSE_DATABASE=posthog
      - KAFKA_URL=kafka://posthog_kafka:9092
      - SITE_URL=https://${ANALYTICS_HOSTNAME}
    depends_on:
      - posthog_db
      - posthog_redis
      - posthog_clickhouse
      - posthog_kafka
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m
    networks:
      - tooling_net

networks:
  tooling_net:
    driver: bridge
  traefik_public:
    external: true

volumes:
  strapi_pg_data:
  strapi_data:
  posthog_pg_data:
  posthog_clickhouse_data:
