#!/bin/bash
# Quick Re-enable ClamAV and FTS
# Since server has 11GB RAM, we can safely re-enable these services

set -euo pipefail

MAILCOW_DIR="/home/comzis/mailcow"
CONFIG_FILE="$MAILCOW_DIR/mailcow.conf"

echo "========================================="
echo "Re-enable ClamAV and FTS"
echo "========================================="
echo ""
echo "Server has 11GB RAM (sufficient for ClamAV + FTS)"
echo "Recommended: 6GB-8GB"
echo ""
echo "This script will:"
echo "  1. Re-enable ClamAV (SKIP_CLAMD=n)"
echo "  2. Re-enable FTS (SKIP_FTS=n)"
echo "  3. Restart Mailcow services"
echo ""
echo "Run this script ON THE SERVER:"
echo ""
echo "ssh comzis@100.83.222.69"
echo "sudo bash /path/to/this/script.sh"
echo ""
echo "Or run these commands manually:"
echo ""
echo "# Re-enable ClamAV"
echo "sudo sed -i 's/^SKIP_CLAMD=y/SKIP_CLAMD=n/' $CONFIG_FILE"
echo ""
echo "# Re-enable FTS"
echo "sudo sed -i 's/^SKIP_FTS=y/SKIP_FTS=n/' $CONFIG_FILE"
echo ""
echo "# Verify changes"
echo "sudo grep -E '^SKIP_CLAMD=|^SKIP_FTS=' $CONFIG_FILE"
echo ""
echo "# Restart services"
echo "cd $MAILCOW_DIR"
echo "docker compose up -d"
echo ""
echo "# Wait and verify"
echo "sleep 60"
echo "docker ps --filter 'name=clamd' --format 'table {{.Names}}\t{{.Status}}'"
echo "docker ps --filter 'name=dovecot' --format 'table {{.Names}}\t{{.Status}}'"
