#!/bin/bash
#
# Configure PostgreSQL standby server for streaming replication
# Sets up standby database that receives WAL from primary
#
# Usage: sudo ./scripts/ha/setup-postgres-standby.sh --primary-ip <ip> --replication-password <password>
# Prerequisites:
#   - PostgreSQL installed but not initialized (or data directory empty)
#   - Primary server configured for replication
#   - Network connectivity to primary server

set -e

if [ "$EUID" -ne 0 ]; then 
   echo "ERROR: This script must be run as root (use sudo)"
   exit 1
fi

# Parse arguments
PRIMARY_IP=""
REPLICATION_PASSWORD=""
REPLICATION_USER="${REPLICATION_USER:-replicator}"
REPLICATION_SLOT="${REPLICATION_SLOT:-standby_slot}"
PG_VERSION="${PG_VERSION:-15}"
PG_DATA_DIR="/var/lib/postgresql/${PG_VERSION}/main"
PG_CONFIG="/etc/postgresql/${PG_VERSION}/main/postgresql.conf"

while [[ $# -gt 0 ]]; do
    case $1 in
        --primary-ip)
            PRIMARY_IP="$2"
            shift 2
            ;;
        --replication-password)
            REPLICATION_PASSWORD="$2"
            shift 2
            ;;
        --replication-user)
            REPLICATION_USER="$2"
            shift 2
            ;;
        --replication-slot)
            REPLICATION_SLOT="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate required parameters
if [ -z "$PRIMARY_IP" ]; then
    echo "ERROR: --primary-ip is required"
    exit 1
fi

if [ -z "$REPLICATION_PASSWORD" ]; then
    read -sp "Enter replication password: " REPLICATION_PASSWORD
    echo ""
    if [ -z "$REPLICATION_PASSWORD" ]; then
        echo "ERROR: Replication password is required"
        exit 1
    fi
fi

echo "=========================================="
echo "  PostgreSQL Standby Replication Setup"
echo "=========================================="
echo ""
echo "Primary server IP: $PRIMARY_IP"
echo "Replication user: $REPLICATION_USER"
echo "Replication slot: $REPLICATION_SLOT"
echo "PostgreSQL version: $PG_VERSION"
echo ""

# Test connectivity to primary
echo "Testing connectivity to primary server..."
if ! timeout 5 bash -c "echo > /dev/tcp/$PRIMARY_IP/5432" 2>/dev/null; then
    echo "❌ ERROR: Cannot connect to primary server at $PRIMARY_IP:5432"
    echo "Please verify:"
    echo "  1. Primary server is running"
    echo "  2. Network connectivity is available"
    echo "  3. PostgreSQL port 5432 is accessible"
    exit 1
fi
echo "✓ Primary server is reachable"
echo ""

# Stop PostgreSQL if running
if systemctl is-active --quiet postgresql; then
    echo "Stopping PostgreSQL..."
    systemctl stop postgresql
    sleep 2
fi

# Backup existing data if present
if [ -d "$PG_DATA_DIR" ] && [ "$(ls -A $PG_DATA_DIR)" ]; then
    echo "⚠️  WARNING: Data directory is not empty"
    read -p "Backup existing data? (yes/no): " BACKUP_EXISTING
    if [ "$BACKUP_EXISTING" = "yes" ]; then
        BACKUP_DIR="/root/postgres-data-backup-$(date +%Y%m%d-%H%M%S)"
        echo "Backing up existing data to: $BACKUP_DIR"
        mv "$PG_DATA_DIR" "$BACKUP_DIR"
        mkdir -p "$PG_DATA_DIR"
        chown postgres:postgres "$PG_DATA_DIR"
        echo "✓ Backup created"
    else
        echo "ERROR: Data directory must be empty for standby setup"
        exit 1
    fi
    echo ""
fi

# Ensure data directory exists and is empty
if [ ! -d "$PG_DATA_DIR" ]; then
    mkdir -p "$PG_DATA_DIR"
    chown postgres:postgres "$PG_DATA_DIR"
fi

# Perform base backup from primary
echo "Performing base backup from primary server..."
echo "This may take several minutes..."

sudo -u postgres pg_basebackup \
    -h "$PRIMARY_IP" \
    -D "$PG_DATA_DIR" \
    -U "$REPLICATION_USER" \
    -v \
    -P \
    -W \
    --wal-method=stream \
    --slot="$REPLICATION_SLOT" <<< "$REPLICATION_PASSWORD" || {
    echo "❌ ERROR: Base backup failed"
    echo "Please verify:"
    echo "  1. Replication user and password are correct"
    echo "  2. Replication slot exists on primary"
    echo "  3. Network connectivity is stable"
    exit 1
}

echo "✓ Base backup completed"
echo ""

# Create recovery configuration
echo "Creating recovery configuration..."

# PostgreSQL 12+ uses postgresql.auto.conf instead of recovery.conf
RECOVERY_FILE="$PG_DATA_DIR/postgresql.auto.conf"

cat >> "$RECOVERY_FILE" << EOF
# Standby replication configuration
# Generated by setup-postgres-standby.sh on $(date)

primary_conninfo = 'host=$PRIMARY_IP port=5432 user=$REPLICATION_USER password=$REPLICATION_PASSWORD'
primary_slot_name = '$REPLICATION_SLOT'
EOF

chown postgres:postgres "$RECOVERY_FILE"
chmod 600 "$RECOVERY_FILE"

echo "✓ Recovery configuration created"
echo ""

# Configure postgresql.conf for standby
echo "Configuring postgresql.conf for standby..."

cp "$PG_CONFIG" "$PG_CONFIG.backup-$(date +%Y%m%d-%H%M%S)"

# Enable hot_standby
sed -i 's/^#*hot_standby.*/hot_standby = on/' "$PG_CONFIG"
if ! grep -q "^hot_standby" "$PG_CONFIG"; then
    echo "hot_standby = on" >> "$PG_CONFIG"
fi

echo "✓ postgresql.conf configured"
echo ""

# Start PostgreSQL
echo "Starting PostgreSQL..."
systemctl start postgresql
sleep 3

if systemctl is-active --quiet postgresql; then
    echo "✓ PostgreSQL started successfully"
else
    echo "❌ ERROR: PostgreSQL failed to start"
    echo "Check logs: sudo journalctl -u postgresql -n 50"
    exit 1
fi
echo ""

# Verify replication status
echo "=========================================="
echo "  Verification"
echo "=========================================="
echo ""

sleep 5  # Wait for replication to start

echo "Checking replication status..."
sudo -u postgres psql -c "SELECT pg_is_in_recovery();" || {
    echo "⚠️  Warning: Could not check replication status"
}

echo ""
echo "Replication statistics (from primary - run on primary server):"
echo "  sudo -u postgres psql -c \"SELECT * FROM pg_stat_replication;\""
echo ""

echo "=========================================="
echo "  Standby Replication Setup Complete"
echo "=========================================="
echo ""
echo "Standby server is now receiving replication from: $PRIMARY_IP"
echo ""
echo "Monitor replication with:"
echo "  sudo -u postgres psql -c \"SELECT pg_is_in_recovery();\"  # Should return 't'"
echo ""
echo "To promote this standby to primary (failover):"
echo "  sudo ./scripts/ha/promote-postgres-standby.sh"
echo ""


