#!/bin/bash
# Fix Docker Network Conflict for Mailcow
# Resolves "Pool overlaps with other one" error

set -euo pipefail

echo "========================================="
echo "Fix Docker Network Conflict"
echo "========================================="
echo ""
echo "The network conflict error means the Mailcow network already exists."
echo ""
echo "Solution options:"
echo ""
echo "Option 1: Use existing network (Recommended)"
echo "---------------------------------------------"
echo "cd /home/comzis/mailcow"
echo "docker compose up -d"
echo ""
echo "If that still fails, try:"
echo ""
echo "Option 2: Stop containers first, then start"
echo "--------------------------------------------"
echo "cd /home/comzis/mailcow"
echo "docker compose stop"
echo "docker compose up -d"
echo ""
echo "Option 3: Remove conflicting network (if safe)"
echo "-----------------------------------------------"
echo "# Check what's using the network first:"
echo "docker network inspect mailcow_mailcow-network 2>/dev/null || echo 'Network not found'"
echo ""
echo "# Only if network is not in use, remove it:"
echo "docker network rm mailcow_mailcow-network"
echo "cd /home/comzis/mailcow"
echo "docker compose up -d"
echo ""
echo "Note: The environment variable warnings are expected -"
echo "they'll be loaded from mailcow.conf when compose starts."
