services:
  coolify:
    image: ghcr.io/coollabsio/coolify:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/coolify:/data/coolify
      - /data/coolify/ssh:/var/www/html/storage/app/ssh
      - /data/coolify/applications:/var/www/html/storage/app/applications
      - /data/coolify/databases:/var/www/html/storage/app/databases
      - /data/coolify/backups:/var/www/html/storage/app/backups
    environment:
      - APP_ID=${APP_ID:-coolify}
      - APP_NAME=Coolify
      - APP_ENV=production
      - APP_KEY=${COOLIFY_APP_KEY}
      - APP_URL=https://deploy.inlock.ai
      - DB_CONNECTION=sqlite
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=coolify-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PUSHER_APP_ID=coolify
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
    networks:
      - edge
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coolify.rule=Host(`deploy.${DOMAIN}`)"
      - "traefik.http.routers.coolify.entrypoints=websecure"
      - "traefik.http.routers.coolify.tls.certresolver=le-dns"
      - "traefik.http.routers.coolify.middlewares=secure-headers@file"
      - "traefik.http.services.coolify.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - coolify-redis
      - coolify-postgres

  coolify-redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - coolify_redis:/data
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  coolify-postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=coolify
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=coolify
    volumes:
      - coolify_postgres:/var/lib/postgresql/data
    networks:
      - coolify
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coolify"]
      interval: 30s
      timeout: 5s
      retries: 3

  coolify-soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    restart: always
    environment:
      - SOKETI_DEFAULT_APP_ID=coolify
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6001/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  coolify:
    name: coolify
    driver: bridge

volumes:
  coolify_redis:
  coolify_postgres:
