services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    restart: always
    environment:
      - BASE_URL=https://dashboard.inlock.ai
      - TZ=Europe/Zurich
    volumes:
      - homarr_configs:/app/data/configs
      - homarr_icons:/app/public/icons
      - homarr_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - edge
      - mgmt
    # Traefik router defined in traefik/dynamic/routers.yml (file provider)
    # No Docker labels required because Traefik no longer watches the Docker API
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7575"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  homarr_configs:
  homarr_icons:
  homarr_data:

networks:
  edge:
    external: true
    name: edge
  mgmt:
    external: true
    name: mgmt
