x-default-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-hardening: &hardening
  security_opt:
    - no-new-privileges:true

x-resource-hints: &resource-hints
  deploy:
    resources:
      limits:
        memory: 1g
      reservations:
        memory: 256m

services:
  inlock-ai:
    image: inlock-ai:latest
    restart: always
    env_file:
      - /opt/inlock-ai-secure-mvp/.env.production
      - ../.env
    networks:
      edge: {}
      internal: {}
      mail:
        ipv4_address: 172.24.0.50
    depends_on:
      inlock-db:
        condition: service_healthy
    # Traefik router defined in traefik/dynamic/routers.yml (file provider)
    # Docker labels removed to eliminate dependency on Docker provider (avoids API version issues)
    # Service port configured in traefik/dynamic/services.yml
    labels: []
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3040/api/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    cap_drop:
      - ALL
    user: "1001:1001"
    <<: [*hardening, *default-logging, *resource-hints]

networks:
  edge:
    external: true
  internal:
    external: true
  mail:
    external: true
