services:
  loki:
    image: grafana/loki:2.9.4
    restart: always
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - loki_data:/loki
      - ./logging/loki-config.yaml:/etc/loki/local-config.yaml:ro
    networks:
      - mgmt
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  promtail:
    image: grafana/promtail:2.9.4
    restart: always
    command:
      - "-config.file=/etc/promtail/config.yml"
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logging/promtail-config.yaml:/etc/promtail/config.yml:ro
      - ../logs/promtail-positions:/tmp/promtail
    networks:
      - mgmt
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9080/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  loki_data:
