# Mailu Email Stack
# Provides SMTP, IMAP, webmail, and admin interface
# Security: Hardened containers, secrets management, network isolation

networks:
  mail:
    name: mail
    driver: bridge
  internal:
    external: true
    name: internal
  mgmt:
    external: true
    name: mgmt

secrets:
  mailu-secret-key:
    file: /home/comzis/apps/secrets-real/mailu-secret-key
  mailu-admin-password:
    file: /home/comzis/apps/secrets-real/mailu-admin-password
  mailu-db-password:
    file: /home/comzis/apps/secrets-real/mailu-db-password

volumes:
  mailu_mail_data:
  mailu_webmail_data:
  mailu_dkim_data:
  mailu_rspamd_data:
  mailu_redis_data:
  mailu_postgres_data:
  nginx_logs:  # Front service nginx logs directory

x-default-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-hardening: &hardening
  security_opt:
    - no-new-privileges:true

x-resource-hints: &resource-hints
  deploy:
    resources:
      limits:
        memory: 512m
      reservations:
        memory: 128m

services:
  # Mailu Frontend - Webmail and Admin UI
  mailu-front:
    image: ghcr.io/mailu/nginx@sha256:1f4aa7762c0e4758cdb8c44a64b8f868a9ffea975089de38d29517390fd0d91b
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.24.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=mail-letsencrypt
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_mail_data:/mail
      - mailu_dkim_data:/dkim
      - nginx_logs:/var/lib/nginx  # Writable directory for nginx logs and modules
    links:
      - mailu-webmail:webmail
    networks:
      mail:
        aliases:
          - front
          - mailu-front
      mgmt:
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/health >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 3
      # /var/lib/nginx moved to volume mount (nginx_logs)
    # read_only: true  # Disabled - Mailu needs to write config files at startup
    # cap_drop: ALL removed - nginx needs capabilities to load modules and write logs
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE  # Required for file access and module loading
    # No user override - let container run as root and drop privileges internally
    security_opt:
      - no-new-privileges:false  # Allow privilege dropping
    <<: [*default-logging, *resource-hints]

  # Mailu Postfix - SMTP Server
  # Ports 25, 465, 587 exposed directly (restricted via firewall allowlists)
  mailu-postfix:
    image: ghcr.io/mailu/postfix@sha256:5f92276dc5af71e130847fb43d6e4519b2c7f6c38b926b36374c63df8d52674f
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.24.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=mail-letsencrypt
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    ports:
      - "25:25"    # SMTP
      - "465:465"  # SMTPS
      - "587:587"  # Submission
    volumes:
      - mailu_mail_data:/mail
      - mailu_dkim_data:/dkim
    networks:
      - mail
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD", "postfix", "status"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
      - /var/spool/postfix
      - /var/run
    # read_only: true  # Disabled - Mailu needs to write config files at startup
    # cap_drop: ALL removed - postfix needs capabilities for queue directory operations
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE  # Required for queue directory operations
    # user: "1000:1000"  # Removed - Mailu needs root to write config files at startup
    security_opt:
      - no-new-privileges:false  # Allow privilege dropping
    <<: [*default-logging, *resource-hints]

  # Mailu Dovecot - IMAP Server
  # Ports 143, 993 exposed directly (restricted via firewall allowlists)
  mailu-imap:
    image: ghcr.io/mailu/dovecot@sha256:d089c32e3118479191ae17c3b973f014f1bdc0ebd5db192d1e4f7e41425803c5
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.24.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=mail-letsencrypt
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    ports:
      - "143:143"  # IMAP
      - "993:993"  # IMAPS
    volumes:
      - mailu_mail_data:/mail
    networks:
      - mail
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "doveadm service status >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
      - /var/run
    # read_only: true  # Disabled - Mailu needs to write config files at startup
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - SYS_CHROOT
      - DAC_OVERRIDE
    # No user override - let container run as root and drop privileges internally
    security_opt:
      - no-new-privileges:false  # Allow privilege dropping
    <<: [*default-logging, *resource-hints]

  # Mailu Rspamd - Spam Filtering
  mailu-rspamd:
    image: ghcr.io/mailu/rspamd@sha256:b37566e625c696f2922dd9fa6218160c6422cd4dc93762afc254843c12649ae4
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.24.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=mail-letsencrypt
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_rspamd_data:/var/lib/rspamd
    networks:
      - mail
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:11334/health >/dev/null 2>&1 || exit 0"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    tmpfs:
      - /tmp
      - /var/run
    # read_only: true  # Disabled - Mailu needs to write config files at startup
    # cap_drop:
    #   - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    # user: "1000:1000"  # Removed - Mailu needs root to write config files at startup
    security_opt:
      - no-new-privileges:false  # Override hardening - Mailu needs to read secrets and write configs
    <<: [*default-logging, *resource-hints]

  # Mailu Admin - Admin API
  mailu-admin:
    image: ghcr.io/mailu/admin@sha256:97bc9dc7259c485fcf20bf86809b17e3aee1b236662c2ebee1f2d6c825801400
    restart: always
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - ../.env
    environment:
      - DOMAIN=${DOMAIN:-inlock.ai}
      - HOSTNAMES=mail.${DOMAIN:-inlock.ai}
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - ADMIN_USER=admin
      - ADMIN_PW_FILE=/run/secrets/mailu-admin-password
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.24.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=mail-letsencrypt
      - POSTMASTER=${POSTMASTER:-admin}
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_mail_data:/mail
      - mailu_dkim_data:/dkim
    networks:
      - mail
      - mgmt
    secrets:
      - mailu-secret-key
      - mailu-admin-password
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/ping >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
      - /var/run
    # read_only: true  # Disabled - Mailu needs to write config files at startup
    # cap_drop: ALL removed - admin needs capabilities for setgroups and chown operations
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    # No user override - let container run as root and drop privileges internally
    security_opt:
      - no-new-privileges:false  # Allow privilege dropping (setgroups)
    <<: [*default-logging, *resource-hints]

  # Mailu Redis - Cache and Session Storage
  mailu-redis:
    image: redis@sha256:ee64a64eaab618d88051c3ade8f6352d11531fcf79d9a4818b9b183d8c1d18ba
    restart: always
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - mailu_redis_data:/data
    networks:
      - mail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    tmpfs:
      - /tmp
    # read_only: true  # Disabled - Redis needs to write appendonly files
    # cap_drop: ALL removed - redis needs capabilities to switch users
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
    # No user override - let container run as root and switch to redis user internally
    security_opt:
      - no-new-privileges:false  # Allow user switching
    <<: [*default-logging]

  # Mailu Postgres - Database
  mailu-postgres:
    image: postgres@sha256:a5074487380d4e686036ce61ed6f2d363939ae9a0c40123d1a9e3bb3a5f344b4
    restart: always
    environment:
      - POSTGRES_DB=mailu
      - POSTGRES_USER=mailu
      - POSTGRES_PASSWORD_FILE=/run/secrets/mailu-db-password
    volumes:
      - mailu_postgres_data:/var/lib/postgresql/data
    networks:
      - mail
      - internal
    secrets:
      - mailu-db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailu -d mailu"]
      interval: 30s
      timeout: 5s
      retries: 5
    tmpfs:
      - /tmp
      - /var/run/postgresql
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:false
    <<: [*default-logging, *resource-hints]


  # Webmail (Roundcube)
  mailu-webmail:
    image: ghcr.io/mailu/webmail:2.0
    restart: always
    env_file:
      - ../.env
    environment:
      - DOMAIN=inlock.ai
      - HOSTNAMES=mail.inlock.ai
      - SECRET_KEY_FILE=/run/secrets/mailu-secret-key
      - DB_HOST=mailu-postgres
      - DB_USER=mailu
      - DB_PW_FILE=/run/secrets/mailu-db-password
      - DB_NAME=mailu
      - REDIS_HOST=mailu-redis
      - REDIS_PORT=6379
      - TZ=UTC
      - SUBNET=172.24.0.0/16
      - LOG_LEVEL=INFO
      - TLS_FLAVOR=mail-letsencrypt
      - POSTMASTER=admin
      - MESSAGE_SIZE_LIMIT=52428800
      - WEBROOT=/
    volumes:
      - mailu_webmail_data:/data
    networks:
      mail:
        aliases:
          - webmail
    secrets:
      - mailu-secret-key
      - mailu-db-password
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/ping']
      interval: 30s
      timeout: 5s
      retries: 3
    # read_only: true
    security_opt:
      - no-new-privileges:true
    <<: [*default-logging]
