services:
  n8n:
    image: n8nio/n8n@sha256:a6d2c1b991a2c1f289d9c63b11fe5fd59c77421fb0c6701e0febc305cd2aa14b
    restart: always
    env_file:
      - ../.env
    environment:
      - N8N_ENCRYPTION_KEY_FILE=/run/secrets/n8n_encryption_key
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD_FILE=/run/secrets/n8n-db-password
      - N8N_EDITOR_BASE_URL=https://n8n.
      - WEBHOOK_URL=https://n8n.
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - edge
      - internal
    secrets:
      - n8n-db-password
      - n8n-encryption-key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.inlock.ai`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=le-dns"
      - "traefik.http.routers.n8n.middlewares=secure-headers@file,allowed-admins@file,mgmt-ratelimit@file"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:5678/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 256m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  edge:
    external: true
    name: edge
  internal:
    external: true
    name: internal

volumes:
  n8n_data:

secrets:
  n8n-db-password:
    file: /home/comzis/apps/secrets-real/n8n-db-password
  n8n-encryption-key:
    file: /home/comzis/apps/secrets-real/n8n-encryption-key
