#!/bin/bash
# Quick fix: Add MacBook public IP to allowlist

echo "=========================================="
echo "PORTAINER ACCESS FIX"
echo "=========================================="
echo ""
echo "This script helps you add your MacBook's public IP to the allowlist."
echo ""
echo "STEP 1: Find your MacBook's public IP"
echo "--------------------------------------"
echo "On your MacBook, run one of these:"
echo ""
echo "  Option A: Visit in browser:"
echo "    https://ifconfig.me"
echo ""
echo "  Option B: Run in terminal:"
echo "    curl ifconfig.me"
echo ""
echo ""
echo "STEP 2: Share that IP with me"
echo "-------------------------------"
echo "Once you have the IP, I'll add it to the allowlist."
echo ""
echo ""
echo "ALTERNATIVE: Use Tailscale MagicDNS"
echo "-----------------------------------"
echo "Configure Tailscale to resolve .inlock.ai via Tailscale:"
echo "1. Go to Tailscale Admin Console"
echo "2. DNS → MagicDNS"
echo "3. Configure split DNS for *.inlock.ai"
echo ""
