# Mailu Compose Fixes - Ready-to-Apply Snippets
# Copy these sections into compose/mailu.yml

# ============================================================================
# FIX 1: Admin Service - Lines 299-305
# ============================================================================
# REPLACE THIS:
#   cap_drop:
#     - ALL
#   # user: "1000:1000"  # Removed - Mailu needs root to write config files at startup
#   security_opt:
#     - no-new-privileges:false  # Override hardening - Mailu needs to read secrets and write configs

# WITH THIS:
cap_add:
  - NET_BIND_SERVICE  # For binding to ports
  - CHOWN             # For chown operations on /dkim, /data
  - SETGID            # For os.setgroups([])
  - SETUID            # For user switching
# user: "1000:1000"  # Removed - Mailu needs root to write config files at startup
security_opt:
  - no-new-privileges:false  # Override hardening - Mailu needs to read secrets and write configs


# ============================================================================
# FIX 2: Front Service - Lines 87-88 (command section)
# ============================================================================
# ADD THIS after line 59 (environment section) and before volumes:

# Option A: Pre-create directories in command (RECOMMENDED)
# REPLACE any existing command with:
command:
  - /bin/sh
  - -c
  - |
    mkdir -p /var/lib/nginx/logs /var/lib/nginx/modules
    /start.py

# OR Option B: Use volume instead of tmpfs (lines 87-90)
# REPLACE:
#   tmpfs:
#     - /tmp
#     - /var/run
#     - /var/lib/nginx  # Writable directory for nginx logs and modules
# 
# WITH:
tmpfs:
  - /tmp
  - /var/run
# Remove /var/lib/nginx from tmpfs - use volume instead (add to volumes section):
volumes:
  - mailu_mail_data:/mail
  - mailu_dkim_data:/dkim
  - mailu_front_logs:/var/lib/nginx  # Add this volume

# And add to volumes section (line 24-29):
#   mailu_front_logs:


# ============================================================================
# FIX 3: Redis Service - Lines 327-331 (Optional - already working)
# ============================================================================
# REPLACE THIS:
#   cap_drop:
#     - ALL
#   # No user override - let container run as root and switch to redis user internally
#   security_opt:
#     - no-new-privileges:false  # Allow user switching

# WITH THIS:
cap_add:
  - CHOWN
  - SETGID
  - SETUID
# No user override - let container run as root and switch to redis user internally
security_opt:
  - no-new-privileges:false  # Allow user switching

